### ISSUE TITLE
TypeError: buffer.readBigInt64LE is not a function

### ISSUE THREAD

**Issue by alejandrovillen** [ardean/smb2#2]
at Object.exports.parseNumber (/node_modules/@stifani/smb2/dist/protocol/structureUtil.js:52:20)
at Socket.Client.onData (/node_modules/@stifani/smb2/dist/client/Client.js:46:53)
Can you help me?
This occurs when the authenticate function is called.

const client = new smb2.Client(host);
const session = await client.authenticate({
	domain,
	username,
	password
});

**Comment by ardean** [comment]
Hi @alejandrovillen 
Sorry, for the late answer. Seems like you are using an older version of node, which does not support BigInt.
Can you try node **v10** or **above**?
Thank you!
